version: "3.9"
services:
  postgres_news:
    image: postgres:latest
    environment:
      POSTGRES_DB: "feeds"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5400:5432"

  postgres_users:
    image: postgres:latest
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"