version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"